In [3]:
import numpy as np

def diagonally_dominant_check(A):
    n = len(A)
    
    for i in range(n):
        diagonal = abs(A[i][i])
        corners = sum(abs(A[i][j]) for j in range(n) if j != i)
        
        if diagonal < corners:
            return False
            
    return True


In [8]:

n = int(input("Enter the size of the square matrix (n): "))

print("Please enter the matrix row by row (separate numbers with spaces):")

matrix = []
for i in range(n):
    row = list(map(float, input(f"Row {i+1}: ").split()))
    matrix.append(row)

A = np.array(matrix)

# ---- Output ----
result = diagonally_dominant_check(A)

print("\nIs the matrix diagonally dominant?", result)
print(A)

Enter the size of the square matrix (n): 3
Please enter the matrix row by row (separate numbers with spaces):
Row 1: 4 1 1
Row 2: 1 5 1
Row 3: 0 2 6

Is the matrix diagonally dominant? True
[[4. 1. 1.]
 [1. 5. 1.]
 [0. 2. 6.]]
